### ISSUE TITLE
More objective wrappers

### ISSUE THREAD

**Issue by warmist** [vapourismo/luwra#1]
A small suggestion: have a state wrapper that is has every function as it's methods. With implicit cast to lua_State* it could simplify a lot of code (mainly the repeated passing of luwra::X(state,...))

**Comment by vapourismo** [comment]
I have thought about this approach - in fact I've already tried.
A central wrapper, which captures the functionality of the API is nice in terms of coding style, but adds barely any functionality.

The wrapper would only be useful with the root `lua_State`. If an instance pointer is passed from Lua to C++, I'd have to rewrap it to get access to the methods I need. 

Instead of having some functions work on `lua_State` and some methods on the wrapped state, I want all of them to work on the lowest common denominator, which is the `lua_State`.
