### ISSUE TITLE
Missing feature

### ISSUE THREAD

**Issue by paly2** [vapourismo/luwra#3]
Hello, sorry for my bad english,

I'm creating a program with this excellent wrapper, and I realize there is a missing feature: there is no way to know if a variable exists or not (without direct call to the Lua API).

The `luwra::Table` class should include a `template<typename K> bool isNil(K&& key);` method, which returns `true` if the value does not exist (= is nil) and `false` if it exists.

This feature would be very useful to me!
Thank you, paly2

**Comment by vapourismo** [comment]
Yes, you are absolutely right. I'll get right on it.

**Comment by vapourismo** [comment]
I've implemented `Table::has` in 25f66441f15fea16b456065aafe7cb95882a9e58.
It takes a `K&& key` (where `K` is the key type) and returns whether the value at the given key is not `nil`. 

Nevertheless, I urge you to be careful when using features that expose Lua to C++, because of the inherent dynamic typing that comes with Lua.
